[package]
name = "config"
version.workspace = true
edition = "2021"

[dependencies]
bitcoin = { workspace = true }
serde = "1"
serde_json = "1"
serde_derive = "1"
hiro-system-kit = { workspace = true }
num_cpus = "1.16.0"
toml = { version = "0.5.11", features = ["preserve_order"] }
